version: "3.8"

services:

  app:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    command: -p 5432
    env_file:
      - .env
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: postgres