version: "3.8"

services:

  app:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14.1-alpine
    ports:
      - "5436:5436"
    command: -p 5436
    env_file:
      - .env

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/database
    command:
      [ "-path", "/database", "-database",  "postgres://postgres:password@db:5436/postgres?sslmode=disable", "up" ]
